# Generated by Django 3.2.8 on 2021-10-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_comment_reply_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
